apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  labels:
    app: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: gabvotingappacr.azurecr.io/votingapp/result:latest
        ports:
        - containerPort: 80
        env:
        - name: POSTGRES_HOST
          value: "db"
        - name: POSTGRES_DB
          value: "votes"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
      imagePullSecrets:
      - name: acr-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  type: NodePort
  selector:
    app: result
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31001
