apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: gabvotingappacr.azurecr.io/votingapp/worker:latest
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: POSTGRES_HOST
          value: "db"
        - name: POSTGRES_DB
          value: "votes"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
      imagePullSecrets:
      - name: acr-pull-secret
