trigger:
  paths:
    include:
      - vote/*

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'REPLACE_WITH_SERVICE_CONNECTION_ID'
  imageRepository: 'votingapp'
  containerRegistry: 'gabvotingappacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/vote/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  name: 'REPLACE_WITH_SELF_HOSTED_POOL'

stages:
- stage: Build
  displayName: Build the voting App
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)/vote'
        command: 'build'
        Dockerfile: 'vote/Dockerfile'
        tags: '$(tag)'

- stage: Push
  displayName: Push the voting App
  dependsOn: Build
  jobs:
  - job: Push
    displayName: Push
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)/vote'
        command: 'push'
        tags: '$(tag)'

- stage: Update_bash_script
  displayName: Update Bash Script
  dependsOn: Push
  jobs:
  - job: Updating_repo_with_bash
    displayName: Update manifests in Azure Repos
    steps:
    - bash: sudo apt-get update && sudo apt-get install -y dos2unix
      displayName: Install dos2unix
    - bash: |
        dos2unix scripts/updateK8sManifests.sh
        chmod +x scripts/updateK8sManifests.sh
        export AZURE_REPO_HTTPS="$(AZURE_REPO_HTTPS)"
        export AZURE_PAT="$(AZURE_PAT)"
        scripts/updateK8sManifests.sh "vote" "$(containerRegistry)/$(imageRepository)" "$(tag)"
      displayName: Run update script
      env:
        AZURE_PAT: $(AZURE_PAT)
        AZURE_REPO_HTTPS: $(AZURE_REPO_HTTPS)
